import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

// Inter font for sans
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

// Keep Geist Mono for monospace if you need it
const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
